spring.application.name=KavachAR

# Render provides PORT; 8080 is used locally
server.port=${PORT:8080}
server.address=0.0.0.0

# =========================
# Aiven MySQL
# =========================
spring.datasource.url=${AIVEN_URL}

spring.datasource.username=avnadmin
spring.datasource.password=${AIVEN_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET}

# JWT expiration = 1 hour
jwt.expiration=3600000

# Google Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SMTP timeouts
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =========================
# Django Service Authentication
# =========================
django.service-token=${DJANGO_SERVICE_TOKEN}

# =========================
# Certificate Verification
# =========================
app.certificate.verification-url=${CERTIFICATE_VERIFICATION_URL}
